lint:
  nextflow_config:
    - config_defaults:
        - params.ribo_database_manifest
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Avani Bhojwani and Timothy Little
  description: A pipeline for de novo transcriptome assembly of short reads from bulk
    RNA-seq
  force: false
  is_nfcore: true
  name: denovotranscript
  org: nf-core
  outdir: .
  version: 1.3.0dev
